Fix Shutdown
icota/bitcoin pull request #2
Opened 2020-09-13 18:43 UTC by BlockMechanic

Resolves shutdown issue for mobile UI.
~~connect(engine, &QQmlEngine::quit, this, &QApplication::quit)~~
becomes
connect(engine, &QQmlEngine::quit, qApp, &QApplication::quit)

Also prevents segfault caused by referencing uninitialzed pollShutdownTimer

2020-09-14 06:36 UTC, icota requested changes

2020-09-14 06:36 UTC, icota commented on src/qt/bitcoin.cpp
>      pollShutdownTimer->stop();
If you want to properly implement shutdown it's probably no good to ignore its timer... Take a look at what it does for the 'old' GUI and see if we need the same functionality (there is a `detectShutdown`). If it's really not needed then it seems to me that we can get away with just the one #ifdef here

2020-09-15 03:10 UTC, BlockMechanic commented on src/qt/bitcoin.cpp
>      pollShutdownTimer->stop();
OK, I will enable the timer in version and see how it goes.

2020-09-17 07:22 UTC, icota commented on src/qt/bitcoin.cpp
>      pollShutdownTimer->stop();
Looks good! Can you please squash the commits into something called e.g. "Qt: implement mobile UI shutdown"?

2020-09-18 20:09 UTC, BlockMechanic commented on src/qt/bitcoin.cpp
>      pollShutdownTimer->stop();
Ok, I squashed and it's now under suggested name.

2020-09-19 07:15 UTC, merged